# Generated by Django 5.2.16 for issue #422

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("use_cases", "0008_approvaldecision_optional_assessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaCandidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_note", models.TextField(blank=True)),
                (
                    "impact",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "ease",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Validierbarkeit",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("dismissed", "Nicht weiterverfolgt"),
                            ("promoted", "Übernommen"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("triaged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idea_candidates",
                        to="accounts.businessunit",
                    ),
                ),
                (
                    "promoted_use_case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_idea_candidate",
                        to="use_cases.usecase",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_idea_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triaged_idea_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "-created_at"],
                        name="idea_state_created_idx",
                    ),
                    models.Index(
                        fields=["business_unit", "state"],
                        name="idea_bu_state_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("promoted_use_case__isnull", False), ("state", "promoted"))
                            | (
                                ~models.Q(("state", "promoted"))
                                & models.Q(("promoted_use_case__isnull", True))
                            )
                        ),
                        name="idea_promoted_link_matches_state",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(("state", "dismissed"))
                            | ~models.Q(("decision_note", ""))
                        ),
                        name="idea_dismissed_requires_note",
                    ),
                ],
            },
        ),
    ]
