# Generated by Django 5.2.16 on 2026-08-23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMTaskRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("delivery_field_draft", "Delivery-Feldentwurf"),
                            (
                                "origin_consistency_review",
                                "Herkunfts-Konsistenzprüfung",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=64)),
                ("field_key", models.CharField(blank=True, max_length=100)),
                ("source_hash", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=20)),
                ("schema_version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("success", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="openrouter", max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("input_chars", models.PositiveIntegerField(default=0)),
                ("output_chars", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_task_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="LLMTaskQuota",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("context", "Kontext"),
                            ("user", "Benutzer"),
                            ("global", "Global"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quota_date", models.DateField()),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("delivery_field_draft", "Delivery-Feldentwurf"),
                            (
                                "origin_consistency_review",
                                "Herkunfts-Konsistenzprüfung",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("field_key", models.CharField(blank=True, max_length=100)),
                ("calls", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_task_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="llmtaskrun",
            index=models.Index(
                fields=["task_type", "status", "-created_at"],
                name="llm_task_run_task_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmtaskrun",
            index=models.Index(
                fields=["object_type", "object_id", "field_key"],
                name="llm_task_run_object_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmtaskrun",
            index=models.Index(fields=["expires_at"], name="llm_task_run_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="llmtaskrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="running", finished_at__isnull=True)
                    | models.Q(status__in=["success", "failed"], finished_at__isnull=False)
                ),
                name="llm_task_run_status_finished",
            ),
        ),
        migrations.AddIndex(
            model_name="llmtaskquota",
            index=models.Index(
                fields=["scope", "quota_date"],
                name="llm_task_quota_scope_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmtaskquota",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        scope="global",
                        user__isnull=True,
                        task_type="",
                        object_type="",
                        object_id="",
                        field_key="",
                    )
                    | models.Q(
                        scope="user",
                        user__isnull=False,
                        task_type="",
                        object_type="",
                        object_id="",
                        field_key="",
                    )
                    | (
                        models.Q(scope="context", user__isnull=True)
                        & ~models.Q(task_type="")
                        & ~models.Q(object_type="")
                        & ~models.Q(object_id="")
                    )
                ),
                name="llm_task_quota_scope_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmtaskquota",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope="global"),
                fields=("quota_date",),
                name="uniq_llm_task_quota_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmtaskquota",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope="user"),
                fields=("user", "quota_date"),
                name="uniq_llm_task_quota_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmtaskquota",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope="context"),
                fields=(
                    "task_type",
                    "object_type",
                    "object_id",
                    "field_key",
                    "quota_date",
                ),
                name="uniq_llm_task_quota_context",
            ),
        ),
    ]
