# Generated by Django 5.2.16 on 2026-07-19 19:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('use_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('project', 'Projektauftrag'), ('privacy', 'Datenschutzbewertung'), ('security', 'Informationssicherheitsbewertung'), ('legal', 'Rechtsbewertung'), ('technical', 'Technische Dokumentation'), ('pilot', 'Pilotbericht'), ('operations', 'Betriebsdokumentation'), ('contract', 'Lieferantenvertrag'), ('cost', 'Kostenrechnung'), ('decision', 'Entscheidungsvorlage'), ('other', 'Sonstiger Nachweis')], max_length=30)),
                ('url', models.URLField(max_length=1000)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_links', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='use_cases.usecase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvidenceLink',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('label', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('project', 'Projektauftrag'), ('privacy', 'Datenschutzbewertung'), ('security', 'Informationssicherheitsbewertung'), ('legal', 'Rechtsbewertung'), ('technical', 'Technische Dokumentation'), ('pilot', 'Pilotbericht'), ('operations', 'Betriebsdokumentation'), ('contract', 'Lieferantenvertrag'), ('cost', 'Kostenrechnung'), ('decision', 'Entscheidungsvorlage'), ('other', 'Sonstiger Nachweis')], max_length=30)),
                ('url', models.URLField(max_length=1000)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='use_cases.usecase')),
            ],
            options={
                'verbose_name': 'historical evidence link',
                'verbose_name_plural': 'historical evidence links',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('recipient_label', models.CharField(blank=True, max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Versendet'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Übersprungen')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='use_cases.usecase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
