# Generated by Django 5.2.16 on 2026-07-19 19:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('use_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('review_date', models.DateField()),
                ('previous_status', models.CharField(choices=[('idea', 'Idee'), ('review', 'Prüfung'), ('pilot', 'Pilot'), ('operation', 'Betrieb'), ('ended', 'Beendet')], max_length=20)),
                ('new_status', models.CharField(choices=[('idea', 'Idee'), ('review', 'Prüfung'), ('pilot', 'Pilot'), ('operation', 'Betrieb'), ('ended', 'Beendet')], max_length=20)),
                ('decision', models.CharField(choices=[('start_review', 'Prüfung starten'), ('continue', 'Fortführen'), ('start_pilot', 'Pilot starten'), ('go_live', 'Produktiv setzen'), ('pause', 'Pausieren'), ('rework', 'Überarbeiten'), ('return', 'In frühere Phase zurücksetzen'), ('end', 'Beenden')], max_length=30)),
                ('rationale', models.TextField()),
                ('open_actions', models.TextField(blank=True)),
                ('action_due_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='use_cases.usecase')),
            ],
            options={
                'verbose_name': 'historical review',
                'verbose_name_plural': 'historical reviews',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateField()),
                ('previous_status', models.CharField(choices=[('idea', 'Idee'), ('review', 'Prüfung'), ('pilot', 'Pilot'), ('operation', 'Betrieb'), ('ended', 'Beendet')], max_length=20)),
                ('new_status', models.CharField(choices=[('idea', 'Idee'), ('review', 'Prüfung'), ('pilot', 'Pilot'), ('operation', 'Betrieb'), ('ended', 'Beendet')], max_length=20)),
                ('decision', models.CharField(choices=[('start_review', 'Prüfung starten'), ('continue', 'Fortführen'), ('start_pilot', 'Pilot starten'), ('go_live', 'Produktiv setzen'), ('pause', 'Pausieren'), ('rework', 'Überarbeiten'), ('return', 'In frühere Phase zurücksetzen'), ('end', 'Beenden')], max_length=30)),
                ('rationale', models.TextField()),
                ('open_actions', models.TextField(blank=True)),
                ('action_due_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='use_cases.usecase')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
