# Generated by Django 5.2.16 on 2026-07-19 19:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('use_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('basis_version', models.CharField(max_length=100)),
                ('personal_data', models.BooleanField(default=False)),
                ('employee_data', models.BooleanField(default=False)),
                ('automated_person_assessment', models.BooleanField(default=False)),
                ('influences_person_decisions', models.BooleanField(default=False)),
                ('biometric_data', models.BooleanField(default=False)),
                ('safety_critical', models.BooleanField(default=False)),
                ('regulated_product', models.BooleanField(default=False)),
                ('health_safety_rights_impact', models.BooleanField(default=False)),
                ('external_ai_or_cloud', models.BooleanField(default=False)),
                ('generated_external_content', models.BooleanField(default=False)),
                ('human_oversight_planned', models.BooleanField(default=False)),
                ('privacy_review_required', models.BooleanField(default=False)),
                ('security_review_required', models.BooleanField(default=False)),
                ('legal_review_required', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('no_flags', 'Keine besonderen Hinweise festgestellt'), ('clarification', 'Fachliche Klärung erforderlich'), ('privacy', 'Datenschutzprüfung erforderlich'), ('security', 'Informationssicherheitsprüfung erforderlich'), ('legal', 'Rechtliche Prüfung erforderlich'), ('completed', 'Prüfung abgeschlossen')], max_length=30)),
                ('rationale', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_reviews', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_assessments', to='use_cases.usecase')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGovernanceAssessment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('assessment_date', models.DateField()),
                ('basis_version', models.CharField(max_length=100)),
                ('personal_data', models.BooleanField(default=False)),
                ('employee_data', models.BooleanField(default=False)),
                ('automated_person_assessment', models.BooleanField(default=False)),
                ('influences_person_decisions', models.BooleanField(default=False)),
                ('biometric_data', models.BooleanField(default=False)),
                ('safety_critical', models.BooleanField(default=False)),
                ('regulated_product', models.BooleanField(default=False)),
                ('health_safety_rights_impact', models.BooleanField(default=False)),
                ('external_ai_or_cloud', models.BooleanField(default=False)),
                ('generated_external_content', models.BooleanField(default=False)),
                ('human_oversight_planned', models.BooleanField(default=False)),
                ('privacy_review_required', models.BooleanField(default=False)),
                ('security_review_required', models.BooleanField(default=False)),
                ('legal_review_required', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('no_flags', 'Keine besonderen Hinweise festgestellt'), ('clarification', 'Fachliche Klärung erforderlich'), ('privacy', 'Datenschutzprüfung erforderlich'), ('security', 'Informationssicherheitsprüfung erforderlich'), ('legal', 'Rechtliche Prüfung erforderlich'), ('completed', 'Prüfung abgeschlossen')], max_length=30)),
                ('rationale', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('use_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='use_cases.usecase')),
            ],
            options={
                'verbose_name': 'historical governance assessment',
                'verbose_name_plural': 'historical governance assessments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
