# Generated by Django 5.2.16 on 2026-08-03 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Datenschutzprüfung"),
                            ("security", "Informationssicherheitsprüfung"),
                            ("legal", "Rechtsprüfung"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Bestanden"),
                            ("passed_with_conditions", "Bestanden mit Auflagen"),
                            ("failed", "Nicht bestanden"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rationale", models.TextField()),
                ("evidence_url", models.URLField()),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_governance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_reviews",
                        to="use_cases.usecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-created_at"],
            },
        ),
    ]
