# Generated by Django 5.2.16 on 2026-08-04 05:23

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0002_governancereview"),
        ("use_cases", "0006_guided_second_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="governancereview",
            options={"ordering": ["-created_at", "-reviewed_at"]},
        ),
        migrations.AddField(
            model_name="governanceassessment",
            name="legal_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governanceassessment",
            name="privacy_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governanceassessment",
            name="security_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="measures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="responsible_role",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="risks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="screening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_artifacts",
                to="governance.governanceassessment",
            ),
        ),
        migrations.AddField(
            model_name="governancereview",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("completed", "Abgeschlossen"),
                    ("not_relevant", "Nicht relevant"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalgovernanceassessment",
            name="legal_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalgovernanceassessment",
            name="privacy_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalgovernanceassessment",
            name="security_review_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="governancereview",
            name="evidence_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="governancereview",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passed", "Bestanden"),
                    ("passed_with_conditions", "Bestanden mit Auflagen"),
                    ("failed", "Nicht bestanden"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGovernanceReview",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Datenschutzprüfung"),
                            ("security", "Informationssicherheitsprüfung"),
                            ("legal", "Rechtsprüfung"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("completed", "Abgeschlossen"),
                            ("not_relevant", "Nicht relevant"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateField(default=django.utils.timezone.localdate)),
                ("responsible_role", models.CharField(blank=True, max_length=120)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Bestanden"),
                            ("passed_with_conditions", "Bestanden mit Auflagen"),
                            ("failed", "Nicht bestanden"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("rationale", models.TextField()),
                ("risks", models.TextField(blank=True)),
                ("measures", models.TextField(blank=True)),
                ("conditions", models.TextField(blank=True)),
                ("evidence_url", models.URLField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "screening",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="governance.governanceassessment",
                    ),
                ),
                (
                    "use_case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="use_cases.usecase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical governance review",
                "verbose_name_plural": "historical governance reviews",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
