# Generated by Django 5.2.16 on 2026-08-05 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Läuft'), ('success', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], db_index=True, default='running', max_length=20)),
                ('source_revision', models.PositiveIntegerField()),
                ('source_hash', models.CharField(max_length=64)),
                ('capture_type', models.CharField(choices=[('value_stream', 'Value Stream'), ('use_case', 'Use Case')], max_length=20)),
                ('catalog_version', models.CharField(max_length=20)),
                ('answer_schema_version', models.CharField(max_length=20)),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('prompt_version', models.CharField(max_length=20)),
                ('extraction_schema_version', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('contradictions', models.JSONField(blank=True, default=list)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_analyses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='accelerator.capturesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptureFieldSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_object_type', models.CharField(choices=[('value_stream', 'Value Stream'), ('value_stream_stage', 'Value-Stream-Phase'), ('process_analysis', 'Prozessanalyse'), ('solution_option', 'Lösungsoption'), ('use_case', 'Use Case')], max_length=30)),
                ('target_field', models.CharField(max_length=200)),
                ('target_object_id', models.UUIDField(blank=True, null=True)),
                ('target_group_key', models.SlugField(blank=True, max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('text_list', 'Textliste'), ('integer', 'Ganzzahl'), ('decimal', 'Dezimalzahl'), ('enum', 'Auswahlliste'), ('boolean', 'Boolean'), ('date', 'Datum'), ('uuid', 'UUID'), ('reference', 'Referenz')], max_length=20)),
                ('suggested_value', models.JSONField()),
                ('source_question', models.CharField(max_length=100)),
                ('source_excerpt', models.TextField()),
                ('uncertainty', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], max_length=10)),
                ('uncertainty_reason', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accelerator.captureanalysis')),
            ],
            options={
                'ordering': ['target_object_type', 'target_group_key', 'target_field'],
            },
        ),
        migrations.CreateModel(
            name='AcceleratorLLMQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('context', 'Capture Session'), ('user', 'Benutzer'), ('global', 'Global')], max_length=20)),
                ('quota_date', models.DateField()),
                ('calls', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_quotas', to='accelerator.capturesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accelerator_llm_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'quota_date'], name='accel_quota_scope_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope', 'global'), ('session__isnull', True), ('user__isnull', True)), models.Q(('scope', 'user'), ('session__isnull', True), ('user__isnull', False)), models.Q(('scope', 'context'), ('session__isnull', False), ('user__isnull', True)), _connector='OR'), name='valid_accel_quota_scope_owner'), models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('quota_date',), name='uniq_accel_quota_global_date'), models.UniqueConstraint(condition=models.Q(('scope', 'user')), fields=('user', 'quota_date'), name='uniq_accel_quota_user_date'), models.UniqueConstraint(condition=models.Q(('scope', 'context')), fields=('session', 'quota_date'), name='uniq_accel_quota_context_date')],
            },
        ),
        migrations.AddIndex(
            model_name='captureanalysis',
            index=models.Index(fields=['session', 'status', '-created_at'], name='analysis_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='captureanalysis',
            index=models.Index(fields=['requested_by', '-created_at'], name='analysis_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='captureanalysis',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('session', 'source_hash'), name='uniq_running_analysis_source'),
        ),
        migrations.AddConstraint(
            model_name='captureanalysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'running')), models.Q(('finished_at__isnull', False), ('status__in', ['success', 'failed'])), _connector='OR'), name='analysis_status_finished_valid'),
        ),
        migrations.AddIndex(
            model_name='capturefieldsuggestion',
            index=models.Index(fields=['analysis', 'target_object_type', 'target_group_key'], name='suggest_analysis_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='capturefieldsuggestion',
            constraint=models.UniqueConstraint(fields=('analysis', 'target_field', 'target_group_key'), name='uniq_analysis_target_group'),
        ),
    ]
