# Generated by Django 5.2.16 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0002_capture_analysis_and_quotas"),
        ("architecture", "0012_update_value_stream_focus_status_label"),
        ("use_cases", "0006_guided_second_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturesession",
            name="target_use_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capture_sessions",
                to="use_cases.usecase",
            ),
        ),
        migrations.AddField(
            model_name="capturesession",
            name="target_value_stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capture_sessions",
                to="architecture.valuestream",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturesession",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("capture_type", "value_stream"),
                        ("target_use_case__isnull", True),
                    )
                    | models.Q(
                        ("capture_type", "use_case"),
                        ("target_value_stream__isnull", True),
                    )
                ),
                name="capture_target_matches_type",
            ),
        ),
    ]
