# Generated by Django 5.2.16 on 2026-08-06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0003_capture_target_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldAdoptionCandidate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        choices=[
                            ("value_stream", "Value Stream"),
                            ("value_stream_stage", "Value-Stream-Phase"),
                            ("process_analysis", "Prozessanalyse"),
                            ("solution_option", "Lösungsoption"),
                            ("use_case", "Use Case"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_object_id", models.UUIDField()),
                ("target_field", models.CharField(max_length=200)),
                ("proposed_value", models.TextField()),
                ("previous_value", models.TextField(blank=True)),
                ("previous_value_hash", models.CharField(max_length=64)),
                ("target_updated_at", models.DateTimeField()),
                ("source_revision", models.PositiveIntegerField()),
                ("source_hash", models.CharField(max_length=64)),
                ("catalog_version", models.CharField(max_length=20)),
                ("answer_schema_version", models.CharField(max_length=20)),
                ("prompt_version", models.CharField(max_length=20)),
                ("extraction_schema_version", models.CharField(max_length=20)),
                (
                    "suggestion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_candidate",
                        to="accelerator.capturefieldsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["target_object_type", "target_object_id", "target_field"],
                "indexes": [
                    models.Index(
                        fields=["target_object_type", "target_object_id", "target_field"],
                        name="adopt_candidate_target_idx",
                    )
                ],
            },
        ),
    ]
