# Generated by Django 5.2.16 on 2026-08-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0004_field_adoption_candidate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldadoptioncandidate",
            name="error_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fieldadoptioncandidate",
            name="processing_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_field_adoption_candidates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldadoptioncandidate",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldadoptioncandidate",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldadoptioncandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Offen"),
                    ("processing", "In Bearbeitung"),
                    ("adopted", "Übernommen"),
                    ("adopted_edited", "Bearbeitet übernommen"),
                    ("rejected", "Verworfen"),
                    ("conflict", "Konflikt"),
                    ("superseded", "Ersetzt"),
                    ("stale", "Veraltet"),
                    ("failed", "Fehlgeschlagen"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="fieldadoptioncandidate",
            index=models.Index(
                fields=["status", "-created_at"],
                name="adopt_candidate_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldadoptioncandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("target_object_type", "target_object_id", "target_field"),
                name="uniq_open_adoption_target_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldadoptioncandidate",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("processing_by__isnull", False),
                        ("processing_started_at__isnull", False),
                        ("resolved_at__isnull", True),
                        ("status", "processing"),
                    )
                    | models.Q(
                        ("processing_by__isnull", True),
                        ("processing_started_at__isnull", True),
                        ("resolved_at__isnull", True),
                        ("status", "open"),
                    )
                    | models.Q(
                        ("resolved_at__isnull", False),
                        (
                            "status__in",
                            [
                                "adopted",
                                "adopted_edited",
                                "rejected",
                                "conflict",
                                "superseded",
                                "stale",
                                "failed",
                            ],
                        ),
                    )
                ),
                name="adoption_candidate_state_valid",
            ),
        ),
    ]
