# Generated by Django 5.2.16 on 2026-08-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0005_field_adoption_candidate_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldAdoptionAudit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("candidate_id_snapshot", models.UUIDField(unique=True)),
                ("suggestion_id_snapshot", models.UUIDField()),
                ("analysis_id_snapshot", models.UUIDField(db_index=True)),
                ("session_id_snapshot", models.UUIDField(db_index=True)),
                ("actor_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_object_type", models.CharField(max_length=30)),
                ("target_object_id", models.UUIDField()),
                ("target_field", models.CharField(max_length=200)),
                ("previous_value", models.TextField(blank=True)),
                ("previous_value_hash", models.CharField(max_length=64)),
                ("proposed_value", models.TextField(blank=True)),
                ("edited_value", models.TextField(blank=True)),
                ("current_value", models.TextField(blank=True)),
                ("final_value", models.TextField(blank=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("adopt", "Übernehmen"), ("reject", "Verwerfen")],
                        max_length=20,
                    ),
                ),
                ("outcome", models.CharField(max_length=30)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("target_updated_at_changed", models.BooleanField(default=False)),
                ("source_question", models.CharField(blank=True, max_length=100)),
                ("source_excerpt_hash", models.CharField(blank=True, max_length=64)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("catalog_version", models.CharField(max_length=20)),
                ("answer_schema_version", models.CharField(max_length=20)),
                ("prompt_version", models.CharField(max_length=20)),
                ("extraction_schema_version", models.CharField(max_length=20)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_adoption_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_audit_events",
                        to="accelerator.captureanalysis",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accelerator.fieldadoptioncandidate",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_audit_events",
                        to="accelerator.capturesession",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adoption_audit_events",
                        to="accelerator.capturefieldsuggestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_object_type", "target_object_id", "target_field"],
                        name="adopt_audit_target_idx",
                    ),
                    models.Index(
                        fields=["outcome", "-created_at"],
                        name="adopt_audit_outcome_idx",
                    ),
                ],
            },
        ),
    ]
