# Generated by Django 5.2.16 on 2026-08-06 12:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0006_field_adoption_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredAdoptionBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id_snapshot", models.UUIDField(db_index=True)),
                ("analysis_id_snapshot", models.UUIDField(db_index=True)),
                ("actor_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "target_object_type",
                    models.CharField(
                        choices=[("value_stream", "Value Stream"), ("use_case", "Use Case")],
                        max_length=20,
                    ),
                ),
                ("target_object_id", models.UUIDField()),
                ("source_revision", models.PositiveIntegerField()),
                ("interpretation_version", models.CharField(max_length=20)),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Der Wert muss ein kleingeschriebener SHA-256-Hash sein.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "selected_graph_hash",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Der Wert muss ein kleingeschriebener SHA-256-Hash sein.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("processing", "In Bearbeitung"),
                            ("committed", "Übernommen"),
                            ("rejected", "Verworfen"),
                            ("conflict", "Konflikt"),
                            ("stale", "Veraltet"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("decision_snapshot", models.JSONField(blank=True, default=dict)),
                ("result_snapshot", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("retention_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structured_adoption_batches",
                        to="accelerator.captureanalysis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_structured_adoption_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processing_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_structured_adoption_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structured_adoption_batches",
                        to="accelerator.capturesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StructuredAdoptionItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("local_key", models.SlugField(max_length=100)),
                (
                    "candidate_kind",
                    models.CharField(
                        choices=[
                            ("metric_set", "Metrikgruppe"),
                            ("value_stream_stage", "Value-Stream-Phase"),
                            ("process_analysis", "Prozessanalyse"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_path", models.CharField(blank=True, max_length=200)),
                ("target_group_key", models.SlugField(blank=True, max_length=100)),
                ("dependency_key_snapshot", models.SlugField(blank=True, max_length=100)),
                ("proposed_snapshot", models.JSONField(blank=True, default=dict)),
                ("interpretation_snapshot", models.JSONField(blank=True, default=dict)),
                ("decision_snapshot", models.JSONField(blank=True, default=dict)),
                ("field_snapshot", models.JSONField(blank=True, default=dict)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("confirmed", "Bestätigt"),
                            ("rejected", "Verworfen"),
                            ("ambiguous", "Unklar"),
                            ("invalid", "Ungültig"),
                            ("dependency_invalid", "Abhängigkeit ungültig"),
                            ("conflict", "Konflikt"),
                            ("stale", "Veraltet"),
                            ("adopted", "Übernommen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("confirmed_proposal", "Vorschlag bestätigt"),
                            ("confirmed_edited", "Bearbeitung bestätigt"),
                            ("current_database", "Aktueller Datenbankwert"),
                            ("rejected", "Verworfen"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("confirmed_by_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_object_id", models.UUIDField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="accelerator.structuredadoptionbatch",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_structured_adoption_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="accelerator.structuredadoptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "local_key"],
            },
        ),
        migrations.CreateModel(
            name="StructuredAdoptionAudit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("batch_id_snapshot", models.UUIDField(db_index=True)),
                ("item_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("session_id_snapshot", models.UUIDField(db_index=True)),
                ("analysis_id_snapshot", models.UUIDField(db_index=True)),
                ("actor_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_object_type", models.CharField(max_length=20)),
                ("target_object_id", models.UUIDField()),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Der Wert muss ein kleingeschriebener SHA-256-Hash sein.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Erstellt"),
                            ("confirmed", "Bestätigt"),
                            ("rejected", "Verworfen"),
                            ("committed", "Übernommen"),
                            ("conflict", "Konflikt"),
                            ("failed", "Fehlgeschlagen"),
                            ("retained", "Aufbewahrt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("outcome", models.CharField(max_length=30)),
                ("step", models.CharField(blank=True, max_length=50)),
                ("item_kind", models.CharField(blank=True, max_length=30)),
                ("item_local_key", models.SlugField(blank=True, max_length=100)),
                ("target_field", models.CharField(blank=True, max_length=200)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structured_adoption_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accelerator.structuredadoptionbatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="accelerator.structuredadoptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="structuredadoptionbatch",
            index=models.Index(
                fields=["target_object_type", "target_object_id", "status"],
                name="structured_batch_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="structuredadoptionbatch",
            index=models.Index(
                fields=["session_id_snapshot", "-created_at"], name="structured_batch_session_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="structuredadoptionbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("processing_by__isnull", True),
                        ("processing_started_at__isnull", True),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("processing_by__isnull", False),
                        ("processing_started_at__isnull", False),
                        ("status", "processing"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("status__in", ["committed", "rejected", "conflict", "stale", "failed"]),
                    ),
                    _connector="OR",
                ),
                name="structured_batch_state_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="structuredadoptionitem",
            index=models.Index(
                fields=["batch", "candidate_kind", "status"], name="structured_item_kind_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="structuredadoptionitem",
            index=models.Index(fields=["batch", "target_path"], name="structured_item_path_idx"),
        ),
        migrations.AddConstraint(
            model_name="structuredadoptionitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "local_key"), name="uniq_structured_item_local_key"
            ),
        ),
        migrations.AddIndex(
            model_name="structuredadoptionaudit",
            index=models.Index(
                fields=["batch_id_snapshot", "-created_at"], name="structured_audit_batch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="structuredadoptionaudit",
            index=models.Index(
                fields=["event", "outcome", "-created_at"], name="structured_audit_event_idx"
            ),
        ),
    ]
