# Generated by Django 5.2.16 on 2026-08-07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0007_structured_adoption_persistence"),
        ("architecture", "0013_solutionoption_not_assessed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acceleratorllmquota",
            name="process_analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_quotas",
                to="architecture.processanalysis",
            ),
        ),
        migrations.AlterField(
            model_name="acceleratorllmquota",
            name="scope",
            field=models.CharField(
                choices=[
                    ("context", "Kontext"),
                    ("user", "Benutzer"),
                    ("global", "Global"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="acceleratorllmquota",
            name="valid_accel_quota_scope_owner",
        ),
        migrations.AddConstraint(
            model_name="acceleratorllmquota",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        scope="global",
                        user__isnull=True,
                        session__isnull=True,
                        process_analysis__isnull=True,
                    )
                    | models.Q(
                        scope="user",
                        user__isnull=False,
                        session__isnull=True,
                        process_analysis__isnull=True,
                    )
                    | models.Q(
                        scope="context",
                        user__isnull=True,
                        session__isnull=False,
                        process_analysis__isnull=True,
                    )
                    | models.Q(
                        scope="context",
                        user__isnull=True,
                        session__isnull=True,
                        process_analysis__isnull=False,
                    )
                ),
                name="valid_accel_quota_scope_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceleratorllmquota",
            constraint=models.UniqueConstraint(
                condition=models.Q(scope="context"),
                fields=("process_analysis", "quota_date"),
                name="uniq_accel_quota_process_date",
            ),
        ),
        migrations.CreateModel(
            name="SolutionGenerationRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("process_version", models.PositiveIntegerField()),
                ("source_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("success", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="openrouter", max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(max_length=20)),
                ("generation_schema_version", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("input_chars", models.PositiveIntegerField(default=0)),
                ("output_chars", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "process_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_generation_runs",
                        to="architecture.processanalysis",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_generation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="solutiongenerationrun",
            index=models.Index(
                fields=["process_analysis", "status", "-created_at"],
                name="solgen_process_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solutiongenerationrun",
            index=models.Index(
                fields=["requested_by", "-created_at"],
                name="solgen_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solutiongenerationrun",
            index=models.Index(fields=["expires_at"], name="solgen_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="solutiongenerationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="running"),
                fields=("process_analysis",),
                name="uniq_running_solution_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="solutiongenerationrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="running", finished_at__isnull=True)
                    | models.Q(
                        status__in=["success", "failed"],
                        finished_at__isnull=False,
                    )
                ),
                name="solution_generation_status_finished_valid",
            ),
        ),
    ]
