# Generated by Django 5.2.16 on 2026-08-09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accelerator", "0009_solutiongenerationrun_preview_payload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionQualityRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("initial_critic", "Initial Critic"),
                            ("repair", "Repair"),
                            ("final_critic", "Final Critic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Läuft"),
                            ("success", "Erfolgreich"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="openrouter", max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(max_length=20)),
                ("output_schema_version", models.CharField(max_length=20)),
                ("input_hash", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("input_chars", models.PositiveIntegerField(default=0)),
                ("output_chars", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solution_quality_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution_generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_runs",
                        to="accelerator.solutiongenerationrun",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="solutionqualityrun",
            index=models.Index(
                fields=["solution_generation_run", "status", "-created_at"],
                name="solquality_run_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="solutionqualityrun",
            index=models.Index(
                fields=["requested_by", "-created_at"],
                name="solquality_user_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="solutionqualityrun",
            constraint=models.UniqueConstraint(
                fields=("solution_generation_run", "step_type"),
                name="uniq_solution_quality_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="solutionqualityrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(status="running", finished_at__isnull=True)
                    | models.Q(
                        status__in=["success", "failed"],
                        finished_at__isnull=False,
                    )
                ),
                name="solution_quality_status_finished_valid",
            ),
        ),
    ]
